---
ansible_ssh_port: 22  # required for my setup

users:
  - user: fraise
    groups: sudo
    name: "Gianni Stubbe"
    ssh_key: "https://github.com/33Fraise33.keys"
  - user: prometheus
    name: "Node Exporter User"
    home: false

nobody:
  group: "65534"
  user: "65534"

ntp: time.cloudflare.com

dns:
  domain: unitix.be
  servers:
    - 1.1.1.1
    - 1.0.0.1
