---
groups:
  - name: generic.rules
    rules:
      - alert: Device offline
        expr: up == 0
        for: 1m
        annotations:
          summary: "Device {{ $labels.node_name }} down (exporter: {{ $labels.job }})"

      - alert: High latency
        expr: probe_icmp_duration_seconds{phase="rtt"} *1000 > 100
        for: 1m
        annotations:
          summary: "Endpoint {{ $labels.node_name }} has high latency: {{ $value }}"

      - alert: Probe Failed
        expr: probe_success != 1
        for: 1m
        annotations:
          summary: "Endpoint {{ $labels.node_name }} is unreachable"
